### ISSUE TITLE
[suggestion] replace Disruptor with JCTools as all you need is a queue

### ISSUE THREAD

**Issue by nitsanw** [xedin/windmill#47]
windmill CPU has a RingBuffer run queue that is demonstrating a Disruptor anti pattern:

    protected <O> Future<O> schedule(Promise<O> promise){
        long sequence = runQueue.next();
        try
        {
            WorkEvent event = runQueue.get(sequence);
            event.setWork(promise);
        }
        finally
        {
            runQueue.publish(sequence);
        }
        return promise.getFuture();
    }
    private class WorkEvent implements Runnable
    {
        private Promise promise;

        public void setWork(Promise promise)
        {
            this.promise = promise;
        }

        public void run()
        {
            promise.fulfil();
            promise = null; // release a reference to already processed promise
        }
    }

This means the route on offering/polling tasks suffers a further dereference for no benefit.
I would be easy to replace by an MPSC queue (https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpscArrayQueue.java) to result in the following:

    protected <O> Future<O> schedule(Promise<O> promise){
        runQueue.offer(promise);
        return promise.getFuture();
    }

Further fallout is to be expected in the HANDLER + run methods, but should be very straight forward. Note that JCTools offers drain methods to enable the pattern you seem to be after. Also note that you can replace the interface reference with a concrete class reference to side-step the type check condition (a load+ predicted branch, but if you care, there it is).
I believe JCTools will deliver better performance in this case as it's a better fit for the use case, happy to PR this.

**Comment by xedin** [comment]
@nitsanw Thanks! I will definitely make it happen!

**Comment by xedin** [comment]
@nitsanw There is also #2 where I want to separate a single runQueue into one-per-CPU to to minimize contention, so maybe it would be a good time to revisit that idea and integrate SPSC queue from JTools collection.

**Comment by nitsanw** [comment]
Cool, you *may* want to consider the growable variant if footprint of the queues is a concern. May or may not be a requirement for you. Also maybe look at the MPSC on SPSC queue which may be what you are after (but it not as polished as the rest, which is why it's in experimental).

**Comment by xedin** [comment]
Integrated!
