### ISSUE TITLE
Windmill is 'high-performance', where are the numbers/benchmarks?

### ISSUE THREAD

**Issue by nitsanw** [xedin/windmill#48]
How do you maintain the claim with no numbers? How do you set course for further improvements?

**Comment by xedin** [comment]
@nitsanw 0.1 has been released a couple of days ago and we are currently working toward making proper benchmarks and releasing the numbers. Also to be frank, and put "high-performance" in perspective, there is nothing in the readme which says that windmill is "high-performance", we just claim that it could be used to build high performance thread-per-core applications.

**Comment by nitsanw** [comment]
@xedin it's a good model for certain things, would be interested in your results. Is the design related to/inspired/informed by Seastar?

**Comment by xedin** [comment]
@nitsanw Totally agree and I'll let you know as soon as we have something! I would say that this project was inspired more by the work that guys at LMAX Exchange are doing (plus Java 8 make a lot of things much more present to work with in this model) and Seastar was taken more as a confirmation/validation that thread-per-core is viable design to implement in practice even with it's drawbacks.

**Comment by nitsanw** [comment]
@xedin @jbellis I believe the Seastar/Scylla work were of interest to the Cassandra project and some talk of moving to a similar runtime was discussed, perhaps a joint effort/feedback could be interesting?

**Comment by smaldini** [comment]
I wonder how it relates to Reactor own ring buffers backed reactive streams Processor, feel free to compare with http://next.projectreactor.io/core/docs/api/reactor/core/publisher/EmitterProcessor.html, http://next.projectreactor.io/core/docs/api/reactor/core/publisher/TopicProcessor.html and http://next.projectreactor.io/core/docs/api/reactor/core/publisher/WorkQueueProcessor.html

**Comment by akarnokd** [comment]
[I did](https://github.com/akarnokd/akarnokd-misc/blob/master/src/jmh/java/hu/akarnokd/comparison/WindmillPerf.java) a small comparative benchmark against the Java ExecutorService and ForkJoinPool, and compared how Rsc's pipelined range does work with a scheduler based on CPU. 

(Benchmarked on i7 4790, Windows 7 x64, Java 8u72)

![image](https://cloud.githubusercontent.com/assets/1269832/13394909/8efb03fc-deeb-11e5-88a5-838d962f47a3.png)

There seems to be something wrong when one schedules 1M tasks as it ends up running with 2000 tasks/s. CPU utilization is 100% for two cores with quite a lot of kernel work.

![image](https://cloud.githubusercontent.com/assets/1269832/13394915/9768f8be-deeb-11e5-96b0-8f5748bd87fb.png)

Here, the ExecutorService is compared against the scheduler created from a CPU and measures the cross-thread pipelining overhead. Windmill's CPU seems to give quite a good response here; I'd guess it uses spin wait strategy.

**Comment by xedin** [comment]
@nitsanw We are definitely on the same page about Cassandra, there is already an issue regarding this https://issues.apache.org/jira/browse/CASSANDRA-10989 and I think we going to work toward possible gradual integration of windmill into Cassandra if community would welcome that. Regarding benchmarks, did you have something specific in mind? It would help us greatly since for the most part what we are trying to do right now is figure out what to benchmark so it doesn't become a presentation of Disruptor performance. We could benchmark different run queue implementations, or were you looking for a higher-level, application benchmark?

**Comment by xedin** [comment]
@akarnokd I have implemented the change suggested by @nitsanw in #47 and have run the benchmark linked above, here is the gist w/ the output - https://gist.github.com/xedin/7a66acd7da72741f9e98. 0.2-SNAPSHOT has been posted to sonatype repository at (https://oss.sonatype.org/content/repositories/snapshots), so you can use it to re-run on your machine as well.

**Comment by nitsanw** [comment]
@xedin @akarnokd Not sure what you can read into these results, but they look good for windmill. Note that forkjoin can execute in same thread or async, where as windmill is always async (I think... is it?):

    Benchmark                 (count)     Score      Error  Units
    WindmillPerf.executor           1  137392.1 ±  34809.5  ops/s
    WindmillPerf.executor        1000    4785.8 ±   1137.9  ops/s
    WindmillPerf.executor     1000000       4.4 ±      0.5  ops/s
    WindmillPerf.forkjoin           1  368288.3 ±  33934.6  ops/s
    WindmillPerf.forkjoin        1000    5921.8 ±   2067.3  ops/s
    WindmillPerf.forkjoin     1000000       7.5 ±      0.5  ops/s
    WindmillPerf.rsc                1   47766.9 ±   2997.4  ops/s
    WindmillPerf.rsc             1000    6894.2 ±    615.3  ops/s
    WindmillPerf.rsc          1000000       7.6 ±      1.9  ops/s
    WindmillPerf.rscWindmill        1  889080.2 ± 182749.9  ops/s
    WindmillPerf.rscWindmill     1000   14355.0 ±   3301.6  ops/s
    WindmillPerf.rscWindmill  1000000      15.4 ±      3.8  ops/s
    WindmillPerf.windmill           1 1445079.2 ± 339985.4  ops/s
    WindmillPerf.windmill        1000   10681.8 ±    737.5  ops/s
    WindmillPerf.windmill     1000000      11.7 ±      0.2  ops/s

Can you do a before/after Disruptor switch with JCTools for me?

**Comment by smaldini** [comment]
```
Benchmark                 (count)   Mode  Cnt        Score         Error  Units
WindmillPerf.executor           1  thrpt    5  3560967.906 ± 1742532.198  ops/s
WindmillPerf.executor        1000  thrpt    5    12827.984 ±    4192.377  ops/s
WindmillPerf.executor     1000000  thrpt    5       12.226 ±       4.765  ops/s
WindmillPerf.forkjoin           1  thrpt    5  1779460.005 ±  446214.086  ops/s
WindmillPerf.forkjoin        1000  thrpt    5     5157.228 ±     394.360  ops/s
WindmillPerf.forkjoin     1000000  thrpt    5        5.907 ±       0.622  ops/s
WindmillPerf.rsc                1  thrpt    5   912991.517 ±  299642.755  ops/s
WindmillPerf.rsc             1000  thrpt    5     8811.931 ±    3700.797  ops/s
WindmillPerf.rsc          1000000  thrpt    5       10.404 ±       2.600  ops/s
WindmillPerf.rscWindmill        1  thrpt    5   523998.019 ±  126326.933  ops/s
WindmillPerf.rscWindmill     1000  thrpt    5    12105.293 ±    2072.273  ops/s
WindmillPerf.rscWindmill  1000000  thrpt    5       12.731 ±       3.856  ops/s
WindmillPerf.windmill           1  thrpt    5  1084285.307 ±  290444.194  ops/s
WindmillPerf.windmill        1000  thrpt    5     7382.447 ±    1911.575  ops/s
WindmillPerf.windmill     1000000  thrpt    5        9.317 ±       0.489  ops/s
```

**Comment by smaldini** [comment]
Looks that Windmill is on par at least with a ring buffer busy spin executor 
`SchedulerGroup.single("b", 1024, WaitStrategy.busySpin())`

**Comment by smaldini** [comment]
Do you have distribution scenario (e.g. Work processor as in Disruptor ? )

**Comment by nitsanw** [comment]
Closer reading of benchmark code, we have some interesting differences between benchmarks:

 - executor: https://github.com/akarnokd/akarnokd-misc/blob/master/src/jmh/java/hu/akarnokd/comparison/WindmillPerf.java#L108 - This could be replaced with an SPSC queue, but would be comparing apples and oranges (which I assume is what SchedulerGroup.single does)
 - rsc/rscWindmill: I think they are comparable to each other. IIUC work is submitted to 1 executor and observed from another. The implications are not clear to me... what work is being carried out of exec2?
 - forkjoin - using the default pool, which leaves the JVM to size the thread pool, so we could be looking at any number of threads depending on host. Also as mentioned before, async execution is left to the framework to decide on.
- windmill - delivering to single executor

**Comment by smaldini** [comment]
No SchedulerGroup is meant to be shared so it uses MPSC, I'm going to add a bench for SPSC. I did a separate bench for SchedulerGroup on https://gist.github.com/smaldini/9ae50662660642f05f75.

RSC does pipelining on two direction, range iteration happens on exec2, range consuming happens on exec1.

**Comment by smaldini** [comment]
But Windmill perfs are good indeed, really on par with what I thought was already maxed out, so now I'm iterating to remove some more volatile and allocation on critical path.

**Comment by xedin** [comment]
@nitsanw Yes, windmill is always async and also forgot to mention that my tests (and I assume others too since at least @akarnokd ran it on Windows) do no take advance for CPU affinity...

**Comment by smaldini** [comment]
ok Comparing with SPSC from reactor-core + RSC, it goes from 11M/s to 17M/s, (I'm on Macbookpro 2.6 i7 16Gb RAM): 
```
Iteration   1: 17.719 ops/s
Iteration   2: 14.486 ops/s
Iteration   3: 16.478 ops/s
Iteration   4: 17.295 ops/s
Iteration   5: 17.662 ops/s
```

**Comment by xedin** [comment]
@smaldini Thanks! I'm currently trying to get most of the functionality I want in place and focus on stability, will keep you guys posted about benchmarks and everything if you are interested.

**Comment by smaldini** [comment]
Fantastic. I wonder also if you guys had GPU pipelining as well in mind, that was an old dream we had in reactor for a couple years but we didn't have any time for it, and since we are focusing on optimizing flows (based on Rx) we will probably never have that time again.

**Comment by akarnokd** [comment]
@nitsanw 

1) executor: rsc/rscWindmill benchmark uses SPSC internally.
2) rsc/rscWindmill: they test the strong pipelining, similar thing you do with your queues where one end of the queue is strictly on one thread and the other is on another thread. In Rx world, this is the way you can pin the two ends of an SPSC queue inside the observeOn operator to different threads.
3) forkjoin: I agree, who knows what it does, but it's not the point, just to have some sanity comparison. 

@xedin 

I rerun the benchmarks with the up-to-date libraries:

![image](https://cloud.githubusercontent.com/assets/1269832/13423172/aed208de-df99-11e5-89e3-bf6d5a33c556.png)

![image](https://cloud.githubusercontent.com/assets/1269832/13423178/b4b38b88-df99-11e5-8f6f-5152a44fe04f.png)

![image](https://cloud.githubusercontent.com/assets/1269832/13423495/8427ea2a-df9b-11e5-96d1-46b44463bf30.png)

![image](https://cloud.githubusercontent.com/assets/1269832/13423533/c89b6ccc-df9b-11e5-98a0-4719c5f0f170.png)

I've added RxJava to the mix. It seems Windmill provides quite a lower overhead, even for the RxJava 1.x, but note that RxJava uses ScheduledExecutorService which has more overhead due to its internal priority queue.

**Comment by xedin** [comment]
@smaldini Yes, we were thinking about GPU pipelining but more as a nice to have... I've re-run the benchmark with the code you've posted in the gist, here is the output https://gist.github.com/xedin/78cf5452bfcfc85932a9

@nitsanw gradle is tricky with snapshots so it's not that straightforward to get benchmark run with the latest code without mpsc, here is the output when I run it with 0.1 (there is a bug I think in 0.1 when 1M is run as the last windmill run it hangs) it should give you an idea what the numbers for disruptor here - https://gist.github.com/xedin/4142f8d3394cf5c8063f

**Comment by nitsanw** [comment]
@xedin @akarnokd I renamed the benchmarks to differentiate submit benchmarks from rsc benchmarks and added the reactor variant. On my laptop (Ubuntu/dual core i5/on battery and noisy...) I ran 5 forks and limited heap to 512m (GC is noisy, don't leave heap to ergonomics). Here's everyone (time unit is ms to make results easier to compare):

Benchmark                    (count)   Mode  Cnt   Score    Error   Units
WindmillPerf.submitExecutor      100  thrpt   25   9.488 ±  3.735  ops/ms
WindmillPerf.submitForkjoin      100  thrpt   25  30.425 ±  6.766  ops/ms
WindmillPerf.rsc                 100  thrpt   25  35.041 ±  3.389  ops/ms
WindmillPerf.rscReactor          100  thrpt   25  35.061 ±  9.425  ops/ms
WindmillPerf.submitReactor       100  thrpt   25  64.016 ± 18.264  ops/ms

Here's Windmill 0.1:
WindmillPerf.rscWindmill         100  thrpt   25  28.726 ±  8.561  ops/ms
WindmillPerf.submitWindmill      100  thrpt   25  26.859 ±  8.770  ops/ms

And 0.2-SNAPSHOT:
Benchmark                    (count)   Mode  Cnt   Score   Error   Units
WindmillPerf.rscWindmill         100  thrpt   25  32.861 ± 10.207  ops/ms
WindmillPerf.submitWindmill      100  thrpt   25  44.354 ± 12.111  ops/ms

The Reactor results are great, but I may have misused it:

        reactor1 = SchedulerGroup.single("b", 1024, WaitStrategy.busySpin());
        reactor2 = SchedulerGroup.single("b", 1024, WaitStrategy.busySpin());
        rscReactor = PublisherBase.range(1, count).subscribeOn(() -> r -> {
            if (r != null) {
                reactor1.accept(r::run);
            }
        }).observeOn(() -> r -> {
            if (r != null) {
                reactor2.accept(r::run);
            }
        });

**Comment by nitsanw** [comment]
@smaldini if your use of Disruptor is similar to Widmill's (i.e. you are using it as a generic queue) you may also want to consider a switch to JCTools (though you might want to consider maturity etc, Disruptor at this stage is better conservative choice probably)

**Comment by smaldini** [comment]
@nitsanw we use both actually :) And we re-implemented the one we use to support backpressure in fact. But there is an extra feature we use from ringBuffer : efficient pub-sub, and replaying (we don't de-reference with these scheduler groups).

**Comment by smaldini** [comment]
The Reactor scheduler group are built for RSC and you can just use `.observeOn(single1)` btw.

**Comment by nitsanw** [comment]
@smaldini awesome! didn't realize you were amongst JCTools illustrious dependants, proud to have you with us :-)

**Comment by nitsanw** [comment]
@smaldini how do you mean re-implemented? anything you want to PR back in?

**Comment by smaldini** [comment]
The Disruptor one I meant, the Queue from JCT tool are simply ported as https://github.com/reactor/reactive-streams-commons/blob/master/src/main/java/reactivestreams/commons/util/SpscArrayQueue.java

**Comment by smaldini** [comment]
Operators such as observeOn use bounded queue suppliers and backpressure from Reactive Streams to never block or spin on producing. Unless you force it.

**Comment by nitsanw** [comment]
@smaldini this right there makes me a sad panda... why not depend on JCTools? there's even an Unsafe free version contributed by @akarnokd

**Comment by smaldini** [comment]
we don't use external dependencies apart from reactive-streams, and that's effectively the one from @akarnokd we use from the project we both maintain :)

**Comment by smaldini** [comment]
The extra reason is that we are meant to be embedded as RxJava or Akka Stream in a lot of apps, in particular Spring 5 apps (see the announce here: https://spring.io/blog/2016/02/16/reactor-2-5-a-second-generation-reactive-foundation-for-the-jvm).

**Comment by nitsanw** [comment]
@smaldini I'm personally opposed to the 'library writers can't use libraries' policy. There's good reasons to use the official and maintained versions of classes you depend on rather than copy and pasting them into your project. The 'single-jar' dependency requirement is not subverted by this, just shade in the dependency. I've had the same discussion with the RxJava folks a while back (and I believe they've come round to agreeing, same as Netty).

**Comment by smaldini** [comment]
@nitsanw funny enough we do that between Reactor 2.5 and Reactive Streams Commons. While Reactor didn't use directly JCTools it appears that we have a couple internal use cases for it, specially the queues that we can't bound (Linked version). But they are package scoped, come from ReactiveStreamCommons which inlines most of what it needs already in 2 classes.

**Comment by smaldini** [comment]
@nitsanw Another reason is that we explore new kind of protocols beyond the queue use you might have with Windmill. We work on fusion (optimizing (a)synchronous stages), we work on batch queue consumer index update (queue protocol), we work on plain java contracts for scheduling (Queue, Supplier<Queue>).

**Comment by nitsanw** [comment]
@smaldini if you need to hack to your own requirements, then you need to get in there, no doubt. From the code to showed me though you have done no such thing (yet). You also fail to credit JCTools or Fast Flow(the original C++ algo) for implementation origin.

**Comment by smaldini** [comment]
Yeah we can fix that credit @akarnokd. TBH, we offer to libraries developper to embed/shadow RSC much more than  this couple util classes that actually were just here for testing purpose at first.

**Comment by nitsanw** [comment]
@smaldini Versioned dependencies are the backbone of the Java ecosystem, I wouldn't give up on them so easily.  I hope Windmill goes that way, and I suggest we take this discussion to a more relevant location.

**Comment by smaldini** [comment]
@nitsanw Sure feel free to re-open an issue on [Reactive Stream Commons](https://github.com/reactor/reactive-streams-commons/issues) !

**Comment by smaldini** [comment]
@nitsanw seems already fixed by @akarnokd https://github.com/reactor/reactive-streams-commons/commit/4047a1065a81dc7a44b0a77b7797ebe0dfc2821a

**Comment by nitsanw** [comment]
@smaldini I hold little hope, but here goes: https://github.com/reactor/reactive-streams-commons/issues/18

**Comment by nitsanw** [comment]
Further issue with the benchmark (at least on machines with low CPU counts) is that the windmill and reactor executors are busy spinning and adding noise to benchmarking each other. I've modified as follows:

    @Setup
    public void setup(BenchmarkParams bp) {
        exec1 = Executors.newSingleThreadExecutor();
        exec2 = Executors.newSingleThreadExecutor();
        rsc = PublisherBase.range(1, count).subscribeOn(exec1).observeOn(exec2);
        if (bp.getBenchmark().endsWith("Windmill")) {
            cs = CPUSet.builder().addSocket(1, 2).build();
            cs.start();

            cpu1 = cs.get(1);
            cpu2 = cs.get(2);
            Callable<Consumer<Runnable>> scheduler1 = () -> r -> {
                if (r != null) {
                    cpu1.schedule(r::run);
                }
            };

            Callable<Consumer<Runnable>> scheduler2 = () -> r -> {
                if (r != null) {
                    cpu2.schedule(r::run);
                }
            };

            rscWindmill = PublisherBase.range(1, count).subscribeOn(scheduler1).observeOn(scheduler2);
        }
        else if (bp.getBenchmark().endsWith("Reactor")) {
            reactor1 = SchedulerGroup.single("b", 1 << 20, WaitStrategy.busySpin());
            reactor2 = SchedulerGroup.single("b", 1 << 20, WaitStrategy.busySpin());
            rscReactor = PublisherBase.range(1, count).subscribeOn(reactor1).observeOn(reactor2);
        }
    }

    @TearDown
    public void teardown() {
        exec1.shutdown();
        exec2.shutdown();
        if (reactor1 != null) {
            reactor1.shutdown();
            reactor2.shutdown();
        }
        if (cs != null){
            cs.halt();
        }
    }

Also note that affinity to same core will adversely effect the windmill benchmark(when affinity works, on linux)

**Comment by xedin** [comment]
I’ve ran updated benchmark on the wider Linux machine (16 physical cores, Xeon @ 2.20GHz) with multiple different heap settings - default, 1G, 4G, 8G here are the results:

(default) https://gist.github.com/xedin/92685f350d913e300610
(1G) https://gist.github.com/xedin/5c97c8b9af1f22cc2bc9
(4G) https://gist.github.com/xedin/999a5e40bb4c94a51c2d
(8G) https://gist.github.com/xedin/01fdd851314c809e3a3a

 The interesting thing I’ve noticed is that "reactor" as well as "rsc_reactor" Error is always very high (except for the last 8G run) and sometimes even bigger than Score itself, according to data from different heap sizes it might be due to GC because throughput of reactor test runs is very inconsistent. Also @nitsanw I’ve made JCTools a dependency on version 1.1 and will keep an eye on when MpscGrowableArrayQueue is released.

**Comment by akarnokd** [comment]
The default `rsc` with 35k ops/s was strangely low for you.

Indeed, the range generates a lot of boxed integers which affects GC. I'll update my benchmark to create less garbage.

**Comment by akarnokd** [comment]
New results:

(i7 4770K, Windows 7 x64, Java 8u72; note, I have access to two machines, the other has i7 4790)

![image](https://cloud.githubusercontent.com/assets/1269832/13456757/fb1ccb68-e064-11e5-9f44-08c665312ea7.png)

![image](https://cloud.githubusercontent.com/assets/1269832/13456767/0a6f07c0-e065-11e5-8962-3af68673e855.png)

**Comment by xedin** [comment]
@akarnokd Thanks! I guess at this point it would be interesting to figure out why reactor (in your runs as well) ends up with such a big error when nothing else does - windmill error is about 5%, forkjoin is about 3% (for count 1 runs and even less for 1K and 1M) where rector does 4M and has an error of 1.5M which is about 33% and 36% for 1K run.

**Comment by xedin** [comment]
@akarnokd I looked into this a bit more today as well and it looks like the main difference comes from the fact that CPU in Windmill does a lot more (networking polling and timer processing) comparing to SchedulerGroup in reactor. Can you please run the benchmark with the latest 0.2 snapshot I've deployed `0.2-20160303.075838-9`? here are my numbers (I've removed network polling and timer processing but the queue is still MpscArrayQueue):

```
Benchmark                  (count)   Mode  Cnt        Score         Error  Units
WindmillPerf.executor            1  thrpt    5   169428.894 ±   16680.404  ops/s
WindmillPerf.executor         1000  thrpt    5     4233.387 ±     101.549  ops/s
WindmillPerf.executor      1000000  thrpt    5        4.388 ±       0.890  ops/s
WindmillPerf.forkjoin            1  thrpt    5   439463.876 ±   71253.511  ops/s
WindmillPerf.forkjoin         1000  thrpt    5     6761.211 ±      26.786  ops/s
WindmillPerf.forkjoin      1000000  thrpt    5        7.518 ±       0.273  ops/s
WindmillPerf.reactor             1  thrpt    5  4350071.703 ±  346147.610  ops/s
WindmillPerf.reactor          1000  thrpt    5    12138.014 ±    2667.235  ops/s
WindmillPerf.reactor       1000000  thrpt    5       12.580 ±       2.299  ops/s
WindmillPerf.rsc                 1  thrpt    5    85783.973 ±    2365.046  ops/s
WindmillPerf.rsc              1000  thrpt    5     7705.382 ±     116.535  ops/s
WindmillPerf.rsc           1000000  thrpt    5        5.851 ±       2.187  ops/s
WindmillPerf.rsc_reactor         1  thrpt    5   434404.576 ± 1290558.424  ops/s
WindmillPerf.rsc_reactor      1000  thrpt    5    10597.975 ±   20745.059  ops/s
WindmillPerf.rsc_reactor   1000000  thrpt    5       15.216 ±       1.827  ops/s
WindmillPerf.rsc_windmill        1  thrpt    5   989054.540 ±    8884.161  ops/s
WindmillPerf.rsc_windmill     1000  thrpt    5    13395.952 ±    1521.513  ops/s
WindmillPerf.rsc_windmill  1000000  thrpt    5       16.435 ±       3.965  ops/s
WindmillPerf.windmill            1  thrpt    5  3313322.542 ±   57270.772  ops/s
WindmillPerf.windmill         1000  thrpt    5     6258.194 ±     231.787  ops/s
WindmillPerf.windmill      1000000  thrpt    5        6.310 ±       0.196  ops/s
```

**Comment by xedin** [comment]
@nitsanw after your changes to MpscOnSpscQueue, I has finally able to test it with all my other changes (disabling of the network pooling, timer-wheel periodic task scheduling and optimized continuations), here are the numbers for MpscArrayQueue (count 1 from the original benchmark):

```
# Run progress: 0.00% complete, ETA 00:00:30
# Fork: 1 of 1
# Warmup Iteration   1: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
3579738.044 ops/s
# Warmup Iteration   2: 3865046.051 ops/s
# Warmup Iteration   3: 3557400.214 ops/s
# Warmup Iteration   4: 4032710.592 ops/s
# Warmup Iteration   5: 3880907.594 ops/s
Iteration   1: 3661050.059 ops/s
Iteration   2: 3971702.865 ops/s
Iteration   3: 3915907.726 ops/s
Iteration   4: 3918937.031 ops/s
Iteration   5: 4000414.221 ops/s

Result "windmill":
  3893602.380 ±(99.9%) 519224.782 ops/s [Average]
  (min, avg, max) = (3661050.059, 3893602.380, 4000414.221), stdev = 134841.027
  CI (99.9%): [3374377.598, 4412827.162] (assumes normal distribution)
```

and here are the numbers for MpscOnSpscQueue:

```
# Run progress: 0.00% complete, ETA 00:00:30
# Fork: 1 of 1
# Warmup Iteration   1: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
3764983.327 ops/s
# Warmup Iteration   2: 4017031.188 ops/s
# Warmup Iteration   3: 3781551.055 ops/s
# Warmup Iteration   4: 4201213.367 ops/s
# Warmup Iteration   5: 3697136.334 ops/s
Iteration   1: 3828992.002 ops/s
Iteration   2: 4301211.478 ops/s
Iteration   3: 4211599.886 ops/s
Iteration   4: 4205778.330 ops/s
Iteration   5: 4275500.368 ops/s

Result "windmill":
  4164616.413 ±(99.9%) 739431.321 ops/s [Average]
  (min, avg, max) = (3828992.002, 4164616.413, 4301211.478), stdev = 192027.966
  CI (99.9%): [3425185.092, 4904047.734] (assumes normal distribution)
```

So MpscOnSpscQueue is definitely better than MpscArrayQueue!

**Comment by nitsanw** [comment]
@xedin for a low core count this will definitely be true. I would think there's a cutoff point where having say 128 CPUs chattering between them will not end well (128 * 128 * queue size). For Java there's no concept of core local or numa node local, but pinned windmill threads could have that, allowing for further topologies maybe.

**Comment by xedin** [comment]
@nitsanw yes, exactly, that is the motivation behind socket/cpu abstractions, I was thinking that if multi-queue design makes performance difference I would have changed MpscOnSpscQueue to take advantage of the topology information and prioritize intra-socket communication vs. inter-socket communication to minimize memory footprint in cost of performance of inter-socket communication.

**Comment by xedin** [comment]
Since this discussion died out and there are more numbers in #56 I'm going to close this one for time being.
